import type { Metadata } from "next";

// style
import "../../public/disc/css/reset.css";
import "../../public/disc/css/normalize.css";
import "../../public/disc/css/style.css";
import "../../public/disc/css/wanted-sans.css";
import Header from "./includes/header";
import Footer from "./includes/footer";
import ToTopBtn from "./includes/ToTopBtn";
import SmoothScroll from "@/components/SmoothScroll";

// header
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <SmoothScroll>
          <Header/>
          {children}
          <Footer/>
        </SmoothScroll>
        <ToTopBtn/>
        </body>
    </html>
  );
}
